FROM alpine:latest

RUN		apk update && apk add --no-cache \
		nginx \
		openssl  && \
		openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
		-subj "/C=FR/ST=IDF/O=42/OU=42/CN=tdesmet.42.fr" \
		-out /etc/ssl/certs/tdesmet.crt \
		-keyout /etc/ssl/private/tdesmet.key

COPY	./conf/nginx.conf		/etc/nginx/nginx.conf

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
